const IMAGE_MAP = {
  'المندي': '/mandi_lamb.jpg',
  'مشويات': '/mixed_grill.jpg',
  'مأكولات بدوية': '/mandi_lamb.jpg',
  'الطيور': '/mixed_grill.jpg',
  'محاشي وطواجن': '/hummus_appetizer.jpg',
  'كنافة': '/hummus_appetizer.jpg',
  'الحلو': '/hummus_appetizer.jpg',
  'الشوربة': '/hummus_appetizer.jpg',
  'مشروبات باردة': '/hummus_appetizer.jpg',
  'مشروبات ساخنة': '/hummus_appetizer.jpg',
};

const SPECIAL_IMAGES = {
  'ريش ضاني': '/lamb_chops.jpg',
  'فخادي ضاني شرائح': '/lamb_chops.jpg',
  'موزة مشوية بالواحدة': '/lamb_chops.jpg',
  'علاقة ضاني (700 جم)': '/lamb_chops.jpg',
  'طاجن بامية بالضاني صغير': '/mandi_lamb.jpg',
  'طاجن بسلة بالضاني': '/mandi_lamb.jpg',
  'طاجن كوارع': '/mandi_lamb.jpg',
  'طاجن عكاوي': '/mandi_lamb.jpg',
  'طاجن ورق عنب بالكوارع': '/mandi_lamb.jpg',
  'طبق مشكل محاشي': '/mandi_lamb.jpg',
  'طبق ممبار': '/mandi_lamb.jpg',
  'طبق جلاش': '/mandi_lamb.jpg',
  'طبق ملوخية خضرا': '/mandi_lamb.jpg',
};

function getImage(item) {
  return SPECIAL_IMAGES[item.title] || IMAGE_MAP[item.category] || '/mixed_grill.jpg';
}

const menuItems = [
  // مشروبات ساخنة
  {
    id: 'hot-1',
    title: 'قهوة',
    description: 'فنجان قهوة تركي بوش مظبوط، يعدل الدماغ بعد الأكلة الدسمة.',
    price: 70,
    category: 'مشروبات ساخنة',
    image: '/menu/turkish-coffee.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'hot-2',
    title: 'قهوة حليب',
    description: 'قهوة فرنساوي بالحليب السخن، خفيفة وتفوقك.',
    price: 70,
    category: 'مشروبات ساخنة',
    image: '/menu/cappuccino.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'hot-3',
    title: 'شاي فتلة',
    description: 'كوباية شاي خفيفة تظبط الأداء وتهضم.',
    price: 40,
    category: 'مشروبات ساخنة',
    image: '/menu/tea.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'hot-4',
    title: 'شاي أخضر زردة',
    description: 'شاي أخضر بدوي معمول على الحطب، يهضم ويريح المعدة.',
    price: 60,
    category: 'مشروبات ساخنة',
    image: '/menu/mint-tea.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'hot-5',
    title: 'شاي أحمر زردة',
    description: 'شاي أحمر زردة تقيل ومخمخ، بتاع القعدة الصح.',
    price: 60,
    category: 'مشروبات ساخنة',
    image: '/menu/tea.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'hot-6',
    title: 'نسكافيه',
    description: 'مج نسكافيه سخن يصحصحك ويظبط مودك.',
    price: 60,
    category: 'مشروبات ساخنة',
    image: '/menu/cappuccino.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'hot-7',
    title: 'كابتشينو',
    description: 'كابتشينو بوش غني وكريمي، لمحبي الروقان.',
    price: 60,
    category: 'مشروبات ساخنة',
    image: '/menu/cappuccino.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'hot-8',
    title: 'كاكاو سخن',
    description: 'مشروب كاكاو دافي وغني بالشوكولاتة، يدفي في برد الشتا.',
    price: 60,
    category: 'مشروبات ساخنة',
    image: '/menu/hot-chocolate.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'hot-9',
    title: 'ينسون',
    description: 'ينسون مغلي فريش، يهدي الأعصاب ويروق البال.',
    price: 60,
    category: 'مشروبات ساخنة',
    image: '/menu/mint-tea.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'hot-10',
    title: 'كركديه',
    description: 'كركديه سخن ومزز، يظبط الضغط والمزاج.',
    price: 60,
    category: 'مشروبات ساخنة',
    image: '/menu/hibiscus.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'hot-11',
    title: 'نعناع',
    description: 'نعناع بلدي مغلي فريش، ريحته لوحدها ترد الروح.',
    price: 60,
    category: 'مشروبات ساخنة',
    image: '/menu/mint-tea.jpg',
    badge: null,
    isPopular: false,
  },

  // مشروبات باردة
  {
    id: 'cold-1',
    title: 'زجاجة ليمون بالنعناع',
    description: 'عصير ليمون فريش مضروب مع نعناع ساقع، يطري على قلبك.',
    price: 100,
    category: 'مشروبات باردة',
    image: '/menu/lemonade.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'cold-2',
    title: 'زجاجة برتقال',
    description: 'عصير برتقال بلدي فريش متلج، كله فيتامينات وانتعاش.',
    price: 100,
    category: 'مشروبات باردة',
    image: '/menu/orange-juice.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'cold-3',
    title: 'زجاجة مانجو',
    description: 'عصير مانجة مركز وتقيل، من بتاع الصيف اللي يروق الدم.',
    price: 130,
    category: 'مشروبات باردة',
    image: '/menu/mango-juice.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'cold-4',
    title: 'زجاجة فراولة',
    description: 'عصير فراولة طازة ومسكر ومضروب صح.',
    price: 100,
    category: 'مشروبات باردة',
    image: '/menu/strawberry-juice.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'cold-5',
    title: 'زجاجة جوافة',
    description: 'عصير جوافة باللبن تقيل ومغذي، طعمه حكاية.',
    price: 100,
    category: 'مشروبات باردة',
    image: '/menu/mango-juice.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'cold-6',
    title: 'زجاجة عناب',
    description: 'عناب ساقع مشبر ومزز، يروي العطش في الحر.',
    price: 90,
    category: 'مشروبات باردة',
    image: '/menu/hibiscus.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'cold-7',
    title: 'مياه معدنية صغيرة',
    description: 'قزازة ماية معدنية صغيرة ساقعة متلجة.',
    price: 15,
    category: 'مشروبات باردة',
    image: '/menu/water-bottle.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'cold-8',
    title: 'شوب عصير فريش',
    description: 'شوب عصير فريش طبيعي، اختار اللي على مزاجك.',
    price: 55,
    category: 'مشروبات باردة',
    image: '/menu/orange-juice.jpg',
    badge: null,
    isPopular: false,
  },

  // الحلو
  {
    id: 'sweet-1',
    title: 'مهلبية',
    description: 'طبق مهلبية بيتي كريمي وعليها رشة مكسرات، بتدوب في البق.',
    price: 60,
    category: 'الحلو',
    image: '/menu/rice-pudding.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'sweet-2',
    title: 'كريم كراميل',
    description: 'كريم كراميل ساقع وناعم بطعم الكراميل المكرمل اللذيذ.',
    price: 70,
    category: 'الحلو',
    image: '/menu/cream-caramel.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'sweet-3',
    title: 'جيلي فواكه',
    description: 'طبق جيلي ساقع متدلع بقطع الفواكه الفريش.',
    price: 40,
    category: 'الحلو',
    image: '/menu/pudding.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'sweet-4',
    title: 'جيلي الماظية',
    description: 'جيلي ألماظية شفاف وخفيف، يحلي بقك بعد الأكل.',
    price: 60,
    category: 'الحلو',
    image: '/menu/pudding.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'sweet-5',
    title: 'أرز باللبن سادة',
    description: 'طبق رز بلبن كريمي وسادة، طعم زمان الأصلي.',
    price: 60,
    category: 'الحلو',
    image: '/menu/rice-pudding.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'sweet-6',
    title: 'أرز باللبن بالفواكه',
    description: 'رز بلبن غرقان في اللبن ومحطوط عليه تشكيلة فواكه طازة.',
    price: 65,
    category: 'الحلو',
    image: '/menu/rice-pudding.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'sweet-7',
    title: 'أرز باللبن فرن',
    description: 'طاجن رز بلبن واخد وش جراتان محمر في الفرن، ريحته تجنن.',
    price: 60,
    category: 'الحلو',
    image: '/menu/rice-pudding.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'sweet-8',
    title: 'كاستر بالشيكولاتة',
    description: 'كاستر شوكولاتة غني وتقيل، لمحبي العظمة والشوكولاتة.',
    price: 60,
    category: 'الحلو',
    image: '/menu/pudding.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'sweet-9',
    title: 'بودنج شيكولاتة',
    description: 'بودنج شوكولاتة ناعم وساقع، بيدوب في البق دوب.',
    price: 60,
    category: 'الحلو',
    image: '/menu/pudding.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'sweet-10',
    title: 'بودنج طوفي',
    description: 'بودنج بطعم التوفي والكراميل، حاجة كده من الآخر.',
    price: 60,
    category: 'الحلو',
    image: '/menu/pudding.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'sweet-11',
    title: 'أم علي',
    description: 'طاجن أم علي متغرق لبن وقشطة ومكسرات، طالع سخن مولع من الفرن.',
    price: 75,
    category: 'الحلو',
    image: '/menu/umm-ali.jpg',
    badge: 'الأكثر طلباً',
    isPopular: true,
    popularOrder: 3,
  },
  {
    id: 'kunafa-1',
    title: 'كنافة قشطة',
    description: 'صينية كنافة سورية متقمرة على الفحم، محشية قشطة بلدي طازة وبتبظ من كل ناحية.',
    price: 150,
    priceNote: 'صغير 150 | وسط 180 | كبير 250',
    category: 'كنافة',
    image: '/menu/kunafa.jpg',
    badge: 'على الفحم',
    isPopular: true,
    popularOrder: 5,
  },
  {
    id: 'kunafa-2',
    title: 'كنافة جبنة',
    description: 'كنافة نابلسية سخنة بالجبنة العكاوي السايحة اللي بتمط معاك لأخر الشارع.',
    price: 150,
    priceNote: 'صغير 150 | وسط 180 | كبير 250',
    category: 'كنافة',
    image: '/menu/kunafa.jpg',
    badge: 'على الفحم',
    isPopular: true,
    popularOrder: 4,
  },
  {
    id: 'bedouin-1',
    title: 'ك ضاني بالأرز أو مبكبكة',
    description: 'لحمة ضاني دايبة دوب، بتنزلك مع رز خلطة أو حلة مكرونة مبكبكة بالصلصة متسبكة على أبوه.',
    price: 575,
    priceNote: '1/2 كيلو 575 | كيلو 1150',
    category: 'مأكولات بدوية',
    image: '/menu/bedouin-meat.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'bedouin-2',
    title: 'ك كندوز بالأرز أو مبكبكة',
    description: 'لحم كندوز بلدي طري، متقدم مع رز مبهر أو مكرونة مبكبكة سخنة تدفي.',
    price: 575,
    priceNote: '1/2 كيلو 575 | كيلو 1150',
    category: 'مأكولات بدوية',
    image: '/menu/bedouin-meat.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'bedouin-3',
    title: 'ك نيفا بالأرز أو مبكبكة',
    description: 'لحم نيفا مخصوص واخد تسوية بدوي صح، مع الرز أو المكرونة الغرقانة في الصلصة.',
    price: 575,
    priceNote: '1/2 كيلو 575 | كيلو 1150',
    category: 'مأكولات بدوية',
    image: '/menu/bedouin-meat.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'bedouin-4',
    title: 'تحميره لحمة بالبصل',
    description: 'طاسة لحمة متحمرة في السمنة البلدي مع البصل المكرمل، ريحتها وطعمها يودوك في حتة تانية.',
    price: 575,
    priceNote: '1/2 كيلو 575 | كيلو 1150',
    category: 'مأكولات بدوية',
    image: '/menu/bedouin-meat.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'bedouin-5',
    title: 'علاقة ضاني (700 جم)',
    description: 'علاقة ضاني بلدي وزن 700 جرام، مشوية ومتبلة تتبيلة بدوية أصيلة تشرفك.',
    price: 800,
    category: 'مأكولات بدوية',
    image: '/menu/lamb-chops.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'bedouin-6',
    title: 'موزة ضاني بالأرز أو المكرونة',
    description: 'موزة ضاني ملبسة ودايبة بتفصل من العضم لوحدها، مع سرفيس رز أو مكرونة.',
    price: 700,
    category: 'مأكولات بدوية',
    image: '/menu/mandi-lamb.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'bedouin-7',
    title: 'طبق أرز أو مكرونة',
    description: 'طبق رز خلطة أو مكرونة بالصلصة، اطلب الحجم اللي يكمل أكلتك ويسد جوعك.',
    price: 100,
    priceNote: 'صغير 100 | وسط 150 | كبير 200',
    category: 'مأكولات بدوية',
    image: '/menu/rice-dish.jpg',
    badge: null,
    isPopular: false,
  },

  // المشويات
  {
    id: 'grill-1',
    title: 'ريش ضاني',
    description: 'ريش ضاني متبلة بمية البصل والبهارات وممشوية على الفحم، تاكل صوابعك وراها.',
    price: 600,
    priceNote: '1/2 كيلو 600 | كيلو 1200',
    category: 'مشويات',
    image: '/menu/lamb-chops.jpg',
    badge: 'الأكثر طلباً',
    isPopular: true,
    popularOrder: 9,
  },
  {
    id: 'grill-2',
    title: 'فخادي ضاني شرائح',
    description: 'شرايح فخدة ضاني طرية ومشوية بتتبيلة الحاتي، مفيش أطعم من كده.',
    price: 600,
    priceNote: '1/2 كيلو 600 | كيلو 1200',
    category: 'مشويات',
    image: '/menu/lamb-chops.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'grill-3',
    title: 'مكس ضاني',
    description: 'تشكيلة من أطعم حتت اللحمة الضاني مشوية على الفحم، ميكس مزاج عالي.',
    price: 600,
    priceNote: '1/2 كيلو 600 | كيلو 1200',
    category: 'مشويات',
    image: '/menu/mixed-grill.jpg',
    badge: 'مميز',
    isPopular: true,
    popularOrder: 8,
  },
  {
    id: 'grill-4',
    title: 'فلتو',
    description: 'عرق فلتو مشوي تسوية مظبوطة، طري جدا وبيدوب في البق من غير مجهود.',
    price: 600,
    priceNote: '1/2 كيلو 600 | كيلو 1200',
    category: 'مشويات',
    image: '/menu/bedouin-meat.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'grill-5',
    title: 'روز بيف',
    description: 'شرايح روز بيف بلدي مشوية على الفحم بطعم خيالي ومقرمشة من برة.',
    price: 550,
    priceNote: '1/2 كيلو 550 | كيلو 1100',
    category: 'مشويات',
    image: '/menu/bedouin-meat.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'grill-6',
    title: 'طرب',
    description: 'صوابع كفتة ملفوفة في المنديل الضاني، بتنزل سمنتها على الفحم وتديك ريحة وطعم ملوش حل.',
    price: 495,
    priceNote: '1/2 كيلو 495 | كيلو 990',
    category: 'مشويات',
    image: '/menu/kebab.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'grill-7',
    title: 'كفتة',
    description: 'كفتة حاتي بلدي على السيخ، متبلة صح الصح ومش بتفك منك.',
    price: 495,
    priceNote: '1/2 كيلو 495 | كيلو 990',
    category: 'مشويات',
    image: '/menu/kofta.jpg',
    badge: null,
    isPopular: true,
    popularOrder: 7,
  },
  {
    id: 'grill-8',
    title: 'مشكل مشوي',
    description: 'كيلو مشكل فيه كفتة ولحمة وطرب، صينية ترضي كل الأذواق وتظبط العيلة.',
    price: 550,
    priceNote: '1/2 كيلو 550 | كيلو 1100',
    category: 'مشويات',
    image: '/menu/mixed-grill.jpg',
    badge: 'للمجموعات',
    isPopular: true,
    popularOrder: 6,
  },
  {
    id: 'grill-9',
    title: 'موزة مشوية بالواحدة',
    description: 'موزة ضاني مشوية سليمة زي ما هي، مقرمشة من برة ودايبة وطعمها غني من جوة.',
    price: 650,
    category: 'مشويات',
    image: '/menu/lamb-chops.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'grill-10',
    title: 'فرخة مشوية',
    description: 'فرخة كاملة مشوية على الفحم ومتبلة بصلصة البصل والطماطم والبهارات اللي بتخش في العضم.',
    price: 450,
    priceNote: '1/2 فرخة 225 | فرخة كاملة 450',
    category: 'مشويات',
    image: '/menu/grilled-chicken.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'grill-11',
    title: 'جوز حمام مشوي',
    description: 'حمام بلدي مفرود ومشوي على الفحم، متبل بخلطة بتخليه مقرمش ولذيذ يتاكل بعضمه.',
    price: 310,
    priceNote: 'فردة 155 | جوز 310',
    category: 'مشويات',
    image: '/menu/pigeon.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'grill-12',
    title: 'سدق بلدي مشوي',
    description: 'سجق بلدي محشي لحمة صافي وتوابل متحبشة، مشوي على الفحم وريحته تجيبك من بعيد.',
    price: 495,
    priceNote: '1/2 كيلو 495 | كيلو 990',
    category: 'مشويات',
    image: '/menu/kebab.jpg',
    badge: null,
    isPopular: false,
  },

  // الطيور
  {
    id: 'birds-1',
    title: 'ديك بلدي بالأرز أو المكرونة',
    description: 'ديك بلدي شامورت متربي على الغالي، مسلوق ومتحمر في السمنة ونازل مع سرفيس رز أو مكرونة.',
    price: 650,
    category: 'الطيور',
    image: '/menu/rooster.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'birds-2',
    title: 'جوز حمام محشي أرز',
    description: 'جوز حمام بلدي جامبو محشي خلطة رز بالكبد والقوانص، ومتحمر في السمنة البلدي لحد ما لونه بقى دهبي.',
    price: 380,
    category: 'الطيور',
    image: '/menu/pigeon.jpg',
    badge: null,
    isPopular: false,
  },

  // المحاشي والطواجن
  {
    id: 'side-1',
    title: 'طبق مشكل محاشي',
    description: 'سرفيس محشي مشكل (كرنب، ورق عنب، بتنجان، فلفل) بخلطة مصرية أصيلة وريحة الشبت والكزبرة مفحفحة.',
    price: 200,
    category: 'محاشي وطواجن',
    image: '/menu/stuffed-grape.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-2',
    title: 'طبق ممبار',
    description: 'طبق ممبار بلدي محشي خلطة رز جبارة، ومتحمر بيقرمش من برة وطري من جوة.',
    price: 200,
    category: 'محاشي وطواجن',
    image: '/menu/macarona.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-3',
    title: 'طبق بطاطس',
    description: 'طبق بطاطس محمرة مقرمشة وفريش، أحلى تسالي جنب الأكل.',
    price: 90,
    category: 'محاشي وطواجن',
    image: '/menu/fries.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-4',
    title: 'طاجن بامية بالضاني صغير',
    description: 'طاجن بامية متسبكة بالصلصة ومضروبالها طشة، وجواها قطع لحمة ضاني دايبة.',
    price: 270,
    category: 'محاشي وطواجن',
    image: '/menu/tagine.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-5',
    title: 'طاجن بسلة بالضاني',
    description: 'طاجن بسلة بالجزر متسبك صح في الفرن مع اللحمة الضاني اللي بتدي للصلصة طعم حكاية.',
    price: 270,
    category: 'محاشي وطواجن',
    image: '/menu/tagine.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-6',
    title: 'طاجن كوارع',
    description: 'طاجن كوارع مخلية متسبكة بالدمعة والبصل في الفرن، حاجة ترم العضم وتلزق الشفايف.',
    price: 330,
    category: 'محاشي وطواجن',
    image: '/menu/tagine.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-7',
    title: 'طاجن عكاوي',
    description: 'طاجن عكاوي بلدي بالبصل مكمور في الفرن لحد ما اللحمة بتدوب وبتبقى زبدة.',
    price: 330,
    category: 'محاشي وطواجن',
    image: '/menu/tagine.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-8',
    title: 'طاجن ورق عنب بالكوارع',
    description: 'ميكس الدمار الشامل.. ورق عنب مزز مرصوص مع كوارع دايبة في طاجن واحد بيغلي في الفرن.',
    price: 330,
    category: 'محاشي وطواجن',
    image: '/menu/tagine.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-9',
    title: 'سمبوسة بالجبنة',
    description: 'حبات سمبوسة مقلية ومقرمشة، محشية ميكس جبن سايحة بتمط معاك.',
    price: 180,
    category: 'محاشي وطواجن',
    image: '/menu/sambousek.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-10',
    title: 'طبق جلاش',
    description: 'قطع جلاش باللحمة المفرومة، مورقة ومقرمشة من برة وطرية ومليانة عصاج من جوة.',
    price: 230,
    category: 'محاشي وطواجن',
    image: '/menu/sambousek.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-11',
    title: 'طبق ورق عنب',
    description: 'طبق ورق عنب ملفوف عالشعرة ومزز، يفتح نفسك على الأكل.',
    price: 210,
    category: 'محاشي وطواجن',
    image: '/menu/stuffed-grape.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'side-12',
    title: 'طبق ملوخية خضرا',
    description: 'طبق ملوخية خضرا معمولها طشة توم وكزبرة، ريحتها تقلب المكان وتتاكل بالعيش أو الرز.',
    price: 80,
    category: 'محاشي وطواجن',
    image: '/menu/molokhia.jpg',
    badge: null,
    isPopular: false,
  },

  // المندي
  {
    id: 'mandi-1',
    title: 'ك ضاني مندي',
    description: 'لحم ضاني مستوي في برميل المندي تحت الأرض، مدخن ودايب زبدة، وبينزل مع الرز البسمتي المبهر.',
    price: 575,
    priceNote: '1/2 كيلو 575 | كيلو 1150',
    category: 'المندي',
    image: '/menu/mandi-lamb.jpg',
    badge: 'الأكثر طلباً',
    isPopular: true,
    popularOrder: 10,
  },
  {
    id: 'mandi-2',
    title: 'ك كندوز مندي',
    description: 'لحم كندوز واخد تسوية مندي بطيئة تحت الأرض، طعم الدخان والتتبيلة واصل لآخر نسيج في اللحمة.',
    price: 565,
    priceNote: '1/2 كيلو 565 | كيلو 1130',
    category: 'المندي',
    image: '/menu/mandi-lamb.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'mandi-3',
    title: 'موزة ضاني مندي',
    description: 'موزة ضاني مستوية بطريقة المندي الأصيلة، اللحمة بتسيب العضم من حلاوتها وتسويتها الصح.',
    price: 700,
    category: 'المندي',
    image: '/menu/mandi-lamb.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'mandi-4',
    title: 'فرخة مندي',
    description: 'فرخة كاملة تسوية مندي بلونها الدهبي الجميل وريحة الفحم والدخان، بتتقدم مع رز مندي بالزبيب.',
    price: 550,
    priceNote: '1/2 فرخة 275 | فرخة كاملة 550',
    category: 'المندي',
    image: '/menu/grilled-chicken.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'mandi-5',
    title: 'تيس صندي (مندي)',
    description: 'تيس كامل مستوي في حفرة المندي، ينفع لعزوماتك الكبيرة والولائم، بتوزنه والسعر بالكيلو.',
    price: 1080,
    priceNote: '1080 سعر الكيلو (حسب الوزن)',
    category: 'المندي',
    image: '/menu/mandi-lamb.jpg',
    badge: 'للمناسبات',
    isPopular: false,
  },
  {
    id: 'mandi-6',
    title: 'نصف تيس صندي (مندي)',
    description: 'نص تيس مندي دايب بالرز والمكسرات لعزومة معتبرة تشرفك قدام ضيوفك.',
    price: 0,
    priceNote: 'السعر حسب الوزن',
    category: 'المندي',
    image: '/menu/mandi-lamb.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'mandi-7',
    title: 'ربع تيس صندي (مندي)',
    description: 'ربع تيس مندي يكفي العيلة ويسد معاك في الطعم والجودة العالية.',
    price: 0,
    priceNote: 'السعر حسب الوزن',
    category: 'المندي',
    image: '/menu/mandi-lamb.jpg',
    badge: null,
    isPopular: false,
  },

  // الشوربة
  {
    id: 'soup-1',
    title: 'شوربة حمام',
    description: 'بولة شوربة حمام دسمة ورايقة ومحبشة بالبهارات، تشربها ترم عضمك وتسند طولك.',
    price: 150,
    category: 'الشوربة',
    image: '/menu/soup.jpg',
    badge: null,
    isPopular: false,
  },
  {
    id: 'soup-2',
    title: 'شوربة كوارع',
    description: 'شوربة كوارع بالبهارات، دفا وتغذية وتظبيط دماغ من أول معلقة.',
    price: 150,
    category: 'الشوربة',
    image: '/menu/soup.jpg',
    badge: null,
    isPopular: false,
  },
];

const categories = [
  { id: 'all', label: 'الكل', priority: 0 },
  { id: 'المندي', label: 'المندي', priority: 100 },
  { id: 'مشويات', label: 'المشويات', priority: 90 },
  { id: 'مأكولات بدوية', label: 'مأكولات بدوية', priority: 80 },
  { id: 'الطيور', label: 'الطيور', priority: 70 },
  { id: 'محاشي وطواجن', label: 'محاشي وطواجن', priority: 60 },
  { id: 'كنافة', label: 'كنافة', priority: 50 },
  { id: 'الحلو', label: 'الحلو', priority: 40 },
  { id: 'الشوربة', label: 'الشوربة', priority: 30 },
  { id: 'مشروبات باردة', label: 'مشروبات باردة', priority: 20 },
  { id: 'مشروبات ساخنة', label: 'مشروبات ساخنة', priority: 10 },
];

const bestSellers = menuItems
  .filter((item) => item.isPopular)
  .sort((a, b) => (b.popularOrder || 0) - (a.popularOrder || 0));

export { menuItems, categories, bestSellers };
